export default {
  login: "Mim1991",
  id: 68198668,
  node_id: "MDQ6VXNlcjY4MTk4NjY4",
  avatar_url: "https://avatars.githubusercontent.com/u/68198668?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Mim1991",
  html_url: "https://github.com/Mim1991",
  followers_url: "https://api.github.com/users/Mim1991/followers",
  following_url: "https://api.github.com/users/Mim1991/following{/other_user}",
  gists_url: "https://api.github.com/users/Mim1991/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Mim1991/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Mim1991/subscriptions",
  organizations_url: "https://api.github.com/users/Mim1991/orgs",
  repos_url: "https://api.github.com/users/Mim1991/repos",
  events_url: "https://api.github.com/users/Mim1991/events{/privacy}",
  received_events_url: "https://api.github.com/users/Mim1991/received_events",
  type: "User",
  site_admin: false,
  name: "Meehir",
  company: "Looking for opportunities & projects!",
  blog: "",
  location: "London",
  email: null,
  hireable: null,
  bio: "Alumni Le Wagon Batch #473\r\n\r\n",
  twitter_username: null,
  public_repos: 32,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: "2020-07-12T17:42:29Z",
  updated_at: "2021-03-20T14:55:40Z",
};
